name: pn0
channels:
  - defaults
dependencies:
  - ca-certificates=2024.12.31
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.21
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - filelock==3.16.1
    - fsspec==2024.12.0
    - jinja2==3.1.5
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.26.4
    - pillow==11.1.0
    - sympy==1.13.3
    - torch==2.2.2
    - torchaudio==2.2.2
    - torchvision==0.17.2
    - typing-extensions==4.12.2
